// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANpALGDa-HNrGsKWyBzzO8baH9Ejtt_tM',
    appId: '1:794864045127:web:809273fb2a256a12d13562',
    messagingSenderId: '794864045127',
    projectId: 'tadatodo-1205',
    authDomain: 'tadatodo-1205.firebaseapp.com',
    storageBucket: 'tadatodo-1205.appspot.com',
    measurementId: 'G-5Q0K0PCF9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_AQAjgYSTIzrtWxAS07wtWLeiP9sBpQk',
    appId: '1:794864045127:android:ac50f0dfcd0f91abd13562',
    messagingSenderId: '794864045127',
    projectId: 'tadatodo-1205',
    storageBucket: 'tadatodo-1205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwvCLn271zaWzXYcLQ_Fh7jaQO8rq67EI',
    appId: '1:794864045127:ios:6132775968ab82f8d13562',
    messagingSenderId: '794864045127',
    projectId: 'tadatodo-1205',
    storageBucket: 'tadatodo-1205.appspot.com',
    iosBundleId: 'com.example.tadatodo',
  );
}
